import assert from "node:assert/strict";
import test from "node:test";

async function render(path = "/") {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}-${path}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request(`http://localhost${path}`, { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

for (const locale of ["zh", "en"]) {
  test(`${locale}: career positioning, complete authors and honest publication groups`, async () => {
    const response = await render(locale === "zh" ? "/" : "/en");
    assert.equal(response.status, 200);
    assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
    const html = await response.text();
    const zh = locale === "zh";
    assert.match(html, zh ? /<html lang="zh-CN">/ : /<html lang="en">/);
    assert.match(html, zh ? /微生物生态与微生物组研究者/ : /Microbial Ecologist &amp; Microbiome Researcher/);
    assert.match(html, zh ? /学位尚未授予/ : /degree not yet awarded/);
    assert.match(html, zh ? /正在寻找微生物生态与微生物组方向的博后/ : /Seeking postdoctoral and related research opportunities/);
    assert.doesNotMatch(html, /PhD in Biochemistry|生物化学博士|dental plaque|牙菌斑|future student opportunities/);
    assert.match(html, /class="capability-strip"/);
    assert.match(html, /class="work-list"/);
    assert.match(html, zh ? /上游生物信息分析由合作者完成/ : /upstream bioinformatics generated by collaborators/);
    assert.doesNotMatch(html, /class="platform-strip"/);
    assert.match(html, /2026\.09/);

    const lists = [...html.matchAll(/<ol class="publication-list"[^>]*>(.*?)<\/ol>/gs)].map((m) => m[1]);
    assert.equal(lists.length, 2);
    const [published, manuscripts] = lists;
    assert.equal((published.match(/class="publication-authors"/g) ?? []).length, 7);
    assert.equal((manuscripts.match(/class="publication-authors"/g) ?? []).length, 2);
    assert.equal((html.match(/<strong>(?:Xiuling Wang|Xiu-Ling Wang)<\/strong>/g) ?? []).length, 9);
    assert.doesNotMatch(published, /IN PREPARATION|准备投稿/);
    assert.doesNotMatch(manuscripts, /Environmental Microbiome|JCR|IF |新锐|XinRui/);
    assert.match(manuscripts, /Applied Soil Ecology/);
    assert.match(manuscripts, /Geoderma/);
    assert.equal((manuscripts.match(zh ? /<em>准备投稿<\/em>/g : /<em>IN PREPARATION<\/em>/g) ?? []).length, 1);
    assert.equal((manuscripts.match(zh ? /<em>已投稿<\/em>/g : /<em>SUBMITTED<\/em>/g) ?? []).length, 1);
    assert.match(manuscripts, /Soil archaeal communities.*?Lars Ganzert.*?Rómulo Oses.*?Dirk Wagner/);
    assert.match(manuscripts, /Scale-dependent organisation.*?Sizhong Yang.*?Lars Ganzert.*?Rómulo Oses.*?Dirk Wagner/);
    assert.doesNotMatch(html, /IN REVIEW|审稿中|LAST AUTHOR|CO-CORRESPONDING|JIF/);

    const order = ["Depth-dependent differences", "Rhizosphere fungal communities", "Mechanical Damage Modulates", "The effects of climate", "Low Temperature", "Bacterial diversity", "A unique mountainous"];
    const positions = order.map((title) => published.indexOf(title));
    assert.ok(positions.every((position, i) => position >= 0 && (i === 0 || position > positions[i - 1])));
    assert.match(published, /Gaodu Liang.*?Li Zhuang/);
    assert.match(published, /Chenyi Mao.*?<strong>Xiuling Wang<\/strong>/);
    assert.match(published, /Zhong-Ping Tian.*?<strong>Xiu-Ling Wang<\/strong>.*?Xiao-Yi Zhao.*?Li Zhuang/);
    assert.match(published, zh ? /一作 &amp; 通讯/ : /FIRST &amp; CORRESPONDING AUTHOR/);
    assert.match(published, zh ? /<b>二作<\/b>/ : /SECOND AUTHOR/);
    assert.match(published, /href="https:\/\/doi.org\/10.1186\/s12866-026-05436-3"/);
    assert.match(published, /href="https:\/\/doi.org\/10.1016\/j.rhisph.2026.101421"/);
    assert.match(published, /Rhizosphere · 39 · 101421/);
    assert.doesNotMatch(html, /authors\.elsevier\.com/);
    assert.equal((published.match(/<details class="journal-metrics">/g) ?? []).length, 7);
    assert.doesNotMatch(published, /<details[^>]*\bopen(?:[ =>])/);
    assert.match(published, /JCR 2025 · IF 3\.9 · Q1/);
    assert.match(published, /IF 8\.0 · Q1/);
    assert.equal((published.match(/class="publication-ranking-xinrui"/g) ?? []).length, 7);

    assert.match(html, /popovertarget="site-qr-popover"/i);
    assert.match(html, /id="site-qr-popover"[^>]*popover="auto"/);
    assert.match(html, /src="\/xiuling-mountains\.webp"/);
    assert.doesNotMatch(html, /class="photo-note"/);
    assert.match(html, /href="#main-content"/);
    assert.match(html, /ORCID.*Google Scholar.*LinkedIn.*ResearchGate.*GitHub/s);
    assert.match(html, /href="\/en\/"/);
    assert.match(html, /href="\/"[^>]*lang="zh-CN"/);
  });
}
