// Public summaries only. Private manuscript sources and correspondence stay outside this repository.
export const selectedWork = [
  {
    id: "rhizosphere",
    title: { zh: "阿魏属植物的根际真菌群落", en: "Rhizosphere fungi of Ferula species" },
    question: { zh: "不同阿魏物种原生生境中的根际真菌群落如何变化？", en: "How do rhizosphere fungal communities vary among Ferula species in their native habitats?" },
    contribution: { zh: "以第一作者及通讯作者身份完成研究与论文写作，连接群落数据分析与根际生态问题。", en: "First and corresponding author, connecting community-data analysis and manuscript writing with questions in rhizosphere ecology." },
    methods: "ITS · Community ecology · R",
    outcome: { zh: "发表于 Rhizosphere，2026", en: "Published in Rhizosphere, 2026" },
    href: "https://doi.org/10.1016/j.rhisph.2026.101421",
  },
  {
    id: "metagenomics",
    title: { zh: "智利土壤宏基因组与环境梯度", en: "Soil metagenomes across Chilean environmental gradients" },
    question: { zh: "土壤微生物功能潜力如何随环境条件和土壤深度变化？", en: "How does soil microbial functional potential vary with environmental conditions and soil depth?" },
    contribution: { zh: "负责下游数据分析、统计、生态解释与论文写作；上游生物信息分析由合作者完成。", en: "Downstream data analysis, statistics, ecological interpretation and manuscript writing, using upstream bioinformatics generated by collaborators." },
    methods: "Metagenomics · Functional profiles · R",
    outcome: { zh: "完整稿件已完成 · 拟投稿 Geoderma", en: "Full manuscript drafted · target journal: Geoderma" },
    href: null,
  },
];
